### ISSUE TITLE
maximum size for tensor at dimension 1 is 1088 but size is 88200

### ISSUE THREAD

**Issue by teodly** [abreuwallace/Stochastic-Restoration-GAN#4]
Trying to run train.py and it doesn't work. Looks like neural network architecture is incompatible with some constrains? Is a specific version of torch library required?
```
[2024-10-04 17:46:10,588][training][ERROR] - Couldn't run Trainer
Traceback (most recent call last):
  File "/dockerx/Stochastic-Restoration-GAN/train.py", line 94, in main
    Trainer(args)
  File "/dockerx/Stochastic-Restoration-GAN/train.py", line 24, in Trainer
    train_dataset = AudioFolder(args.dset.datapath,
  File "/dockerx/Stochastic-Restoration-GAN/src/data/dataset.py", line 88, in __init__
    waveform_chunks = torch.squeeze(waveform_mono.unfold(1, seg_len * self._sample_rate, overlap * self._sample_rate))
RuntimeError: maximum size for tensor at dimension 1 is 1088 but size is 88200
```

**Comment by teodly** [comment]
Something went wrong with my transcoding process, the file was very short, ffprobe reported `Duration: 00:00:00.02, bitrate: 1436 kb/s`. After removing it training started.
